name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Configure AWS Credentials version 4
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
          mask-password: 'false'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.5'
        arguments: build

    - name: Build and push the tagged docker image to Amazon ECR
      env:
          IMAGE_TAG: 'latest'
          IMAGE_NAME: 'github-action-demo'
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          docker push $ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

    - name: SSH to EC2 and pull image
      run: |
          chmod 400 icario.pem
          ssh -o StrictHostKeyChecking=no -i "icario.pem" ubuntu@ec2-3-87-65-7.compute-1.amazonaws.com "docker ps -a; docker pull 321179548224.dkr.ecr.us-east-1.amazonaws.com/github-action-demo:latest; docker images"
